# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G53QiMjyLiw6aihHqnpCraWrZDnMJFj4
"""



from google.colab import files

# This will open a file picker dialog
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

import pandas as pd

# Replace 'your_file.csv' with the actual name of your uploaded file
df = pd.read_csv('/content/supply_chain_dataset1 (1).csv')
display(df.head())

!pip install dash
import dash
from dash import html
import pandas as pd
import plotly.express as px

df["Promotion_Flag"] = df["Promotion_Flag"].map({0: "No Promotion", 1: "Promotion"})

df["Profit"] = (df["Unit_Price"] - df["Unit_Cost"]) * df["Units_Sold"]

sales_avg = df.groupby("Promotion_Flag", as_index=False)["Units_Sold"].mean()

fig_sales = px.bar(
    sales_avg,
    x="Promotion_Flag",
    y="Units_Sold",
    title="Average Units Sold: Promotion vs No Promotion",
    labels={"Units_Sold": "Average Units Sold", "Promotion_Flag": "Promotion Status"}
)

profit_avg = df.groupby("Promotion_Flag", as_index=False)["Profit"].mean()

fig_profit = px.bar(
    profit_avg,
    x="Promotion_Flag",
    y="Profit",
    title="Average Profit: Promotion vs No Promotion",
    labels={"Profit": "Average Profit", "Promotion_Flag": "Promotion Status"}
)

region_promos = df[df["Promotion_Flag"] == "Promotion"] \
    .groupby("Region", as_index=False) \
    .size()

fig_region = px.bar(
    region_promos,
    x="Region",
    y="size",
    title="Number of Promotions by Region",
    labels={"size": "Promotion Count"}
)

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Promotion Impact Analysis Dashboard"),

    html.P(
        "This dashboard analyzes how promotions affect sales volume "
        "and profitability across different regions."
    ),

    html.H3("Sales Impact"),
    html.Div(children=[dash.dcc.Graph(figure=fig_sales)]),

    html.H3("Profit Impact"),
    html.Div(children=[dash.dcc.Graph(figure=fig_profit)]),

    html.H3("Regional Promotion Activity"),
    html.Div(children=[dash.dcc.Graph(figure=fig_region)])
])

if __name__ == "__main__":
    app.run(debug=True)